name: Release

on: { push: { tags: 'v[0-9]+.[0-9]+.[0-9]+*' } }

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: { contents: write, id-token: write }
    env:
      TAG: ${{ github.ref_name }}
      ZIP: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2

      - name: Set env variables
        run: |
          PACKAGE=${GITHUB_REPOSITORY#*/}
          VERSION=${TAG#v}
          VSIX=$PACKAGE-$VERSION.vsix
          echo -e "PACKAGE=$PACKAGE\nVERSION=$VERSION\nZIP=$ZIP\nVSIX=$VSIX" >> $GITHUB_ENV

      - run: bun i
      - run: bun lint
      - run: bun typecheck
      - run: bun build:prod

      - run: bun run package
      - run: zip -r $ZIP package.json LICENSE README.md dist syntaxes
      - run: bun vsce publish --packagePath $VSIX
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - run: gh release create $TAG --title $TAG --draft $ZIP $VSIX
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}